type OmarchyApplicationKind = "native" | "service" | "tui" | "vm" | "web-app";

type OmarchyApplicationAvailability = "base" | "optional" | "preinstall";

export type OmarchyApplication = {
  aliases: readonly string[];
  appsMenu: boolean;
  availability: OmarchyApplicationAvailability;
  description: string;
  executable?: string;
  hotkeys?: readonly string[];
  id: string;
  kind: OmarchyApplicationKind;
  launchUrl?: string;
  launcherLabel?: string;
  manualHref: string;
  name: string;
  websiteUrl?: string;
};

export const omarchyApplications: readonly OmarchyApplication[] = [
  {
    aliases: ["foot", "terminal"],
    appsMenu: true,
    availability: "base",
    description: "Terminal",
    executable: "foot",
    hotkeys: ["Super + Return"],
    id: "foot",
    kind: "native",
    manualHref: "/manual/terminal/",
    name: "Foot",
    websiteUrl: "https://codeberg.org/dnkl/foot",
  },
  {
    aliases: ["nvim", "neovim", "editor"],
    appsMenu: false,
    availability: "base",
    description: "Editor",
    executable: "nvim",
    hotkeys: ["Super + Shift + N"],
    id: "neovim",
    kind: "tui",
    manualHref: "/manual/neovim/",
    name: "Neovim",
    websiteUrl: "https://neovim.io/",
  },
  {
    aliases: ["lazygit"],
    appsMenu: false,
    availability: "base",
    description: "Git TUI",
    executable: "lazygit",
    id: "lazygit",
    kind: "tui",
    manualHref: "/manual/tuis/#lazygit",
    name: "Lazygit",
    websiteUrl: "https://github.com/jesseduffield/lazygit",
  },
  {
    aliases: ["docker", "lazydocker"],
    appsMenu: true,
    availability: "preinstall",
    description: "Docker TUI",
    executable: "omarchy-launch-docker-tui",
    hotkeys: ["Super + Shift + D"],
    id: "docker",
    kind: "tui",
    launcherLabel: "Docker",
    manualHref: "/manual/tuis/#lazydocker",
    name: "Lazydocker",
    websiteUrl: "https://github.com/jesseduffield/lazydocker",
  },
  {
    aliases: ["activity", "btop"],
    appsMenu: false,
    availability: "base",
    description: "System monitor",
    executable: "btop",
    hotkeys: ["Super + Ctrl + T"],
    id: "btop",
    kind: "tui",
    launcherLabel: "Activity",
    manualHref: "/manual/tuis/#btop",
    name: "Btop",
    websiteUrl: "https://github.com/aristocratos/btop",
  },
  {
    aliases: ["herdr"],
    appsMenu: false,
    availability: "base",
    description: "Terminal workspace manager",
    executable: "herdr",
    hotkeys: ["Super + Ctrl + Return"],
    id: "herdr",
    kind: "tui",
    manualHref: "/manual/tuis/#herdr",
    name: "Herdr",
    websiteUrl: "https://github.com/omacom-io/herdr",
  },
  {
    aliases: ["about", "fastfetch"],
    appsMenu: false,
    availability: "base",
    description: "System information",
    executable: "fastfetch",
    id: "fastfetch",
    kind: "tui",
    launcherLabel: "About",
    manualHref: "/manual/tuis/#fastfetch",
    name: "Fastfetch",
    websiteUrl: "https://github.com/fastfetch-cli/fastfetch",
  },
  {
    aliases: ["disk usage", "dua"],
    appsMenu: true,
    availability: "base",
    description: "Disk usage analyzer",
    executable: "dua",
    id: "disk-usage",
    kind: "tui",
    manualHref: "/manual/tuis/#disk-usage",
    name: "Disk Usage",
    websiteUrl: "https://github.com/Byron/dua-cli",
  },
  {
    aliases: ["cliamp", "music tui"],
    appsMenu: true,
    availability: "preinstall",
    description: "Music TUI",
    executable: "cliamp",
    hotkeys: ["Super + Shift + Alt + M"],
    id: "cliamp",
    kind: "tui",
    manualHref: "/manual/tuis/#cliamp",
    name: "Cliamp",
    websiteUrl: "https://www.cliamp.stream/",
  },
  {
    aliases: ["files", "nautilus"],
    appsMenu: true,
    availability: "base",
    description: "File manager",
    executable: "nautilus",
    hotkeys: ["Super + Shift + F"],
    id: "files",
    kind: "native",
    manualHref: "/manual/guis/#files",
    name: "Files",
  },
  {
    aliases: ["obsidian", "notes"],
    appsMenu: true,
    availability: "preinstall",
    description: "Notetaking",
    executable: "obsidian",
    hotkeys: ["Super + Shift + O"],
    id: "obsidian",
    kind: "native",
    manualHref: "/manual/guis/#obsidian",
    name: "Obsidian",
    websiteUrl: "https://obsidian.md/",
  },
  {
    aliases: ["omawrite", "writing"],
    appsMenu: true,
    availability: "preinstall",
    description: "Markdown writer",
    executable: "omawrite",
    hotkeys: ["Super + Shift + W"],
    id: "omawrite",
    kind: "native",
    manualHref: "/manual/guis/#omawrite",
    name: "Omawrite",
    websiteUrl: "https://github.com/omacom-io/omawrite",
  },
  {
    aliases: ["pinta", "image editor"],
    appsMenu: true,
    availability: "preinstall",
    description: "Image editor",
    executable: "pinta",
    id: "pinta",
    kind: "native",
    manualHref: "/manual/guis/#pinta",
    name: "Pinta",
    websiteUrl: "https://www.pinta-project.com/",
  },
  {
    aliases: ["aether", "theme builder"],
    appsMenu: true,
    availability: "preinstall",
    description: "Theme builder",
    executable: "aether",
    id: "aether",
    kind: "native",
    manualHref: "/manual/guis/#aether",
    name: "Aether",
    websiteUrl: "https://github.com/bjarneo/aether",
  },
  {
    aliases: ["localsend", "share"],
    appsMenu: true,
    availability: "base",
    description: "Local file sharing",
    executable: "localsend",
    hotkeys: ["Super + Ctrl + S"],
    id: "localsend",
    kind: "native",
    manualHref: "/manual/guis/#localsend",
    name: "LocalSend",
    websiteUrl: "https://localsend.org/",
  },
  {
    aliases: ["libreoffice", "office"],
    appsMenu: true,
    availability: "preinstall",
    description: "Office suite",
    executable: "libreoffice",
    id: "libreoffice",
    kind: "native",
    manualHref: "/manual/guis/#libreoffice",
    name: "LibreOffice",
    websiteUrl: "https://www.libreoffice.org/",
  },
  {
    aliases: ["calculator", "omacalc"],
    appsMenu: true,
    availability: "preinstall",
    description: "Calculator",
    executable: "omacalc",
    hotkeys: ["Super + Ctrl + Q"],
    id: "omacalc",
    kind: "native",
    manualHref: "/manual/guis/#omacalc",
    name: "Omacalc",
    websiteUrl: "https://github.com/omacom-io/omacalc",
  },
  {
    aliases: ["signal", "signal-desktop"],
    appsMenu: false,
    availability: "optional",
    description: "Messenger",
    executable: "signal-desktop",
    hotkeys: ["Super + Shift + G"],
    id: "signal",
    kind: "native",
    manualHref: "/manual/guis/#signal",
    name: "Signal",
    websiteUrl: "https://signal.org/",
  },
  {
    aliases: ["media player", "mpv"],
    appsMenu: true,
    availability: "base",
    description: "Media player",
    executable: "mpv",
    id: "mpv",
    kind: "native",
    launcherLabel: "Media Player",
    manualHref: "/manual/guis/#mpv",
    name: "mpv",
    websiteUrl: "https://mpv.io/",
  },
  {
    aliases: ["obs", "obs studio"],
    appsMenu: true,
    availability: "preinstall",
    description: "Streaming and recording",
    executable: "obs",
    id: "obs-studio",
    kind: "native",
    manualHref: "/manual/guis/#obs-studio",
    name: "OBS Studio",
    websiteUrl: "https://obsproject.com/",
  },
  {
    aliases: ["kdenlive", "video editor"],
    appsMenu: true,
    availability: "preinstall",
    description: "Video editor",
    executable: "kdenlive",
    id: "kdenlive",
    kind: "native",
    manualHref: "/manual/guis/#kdenlive",
    name: "Kdenlive",
    websiteUrl: "https://kdenlive.org/",
  },
  {
    aliases: ["omacut", "video trimmer"],
    appsMenu: true,
    availability: "preinstall",
    description: "Video trimmer",
    executable: "omacut",
    id: "omacut",
    kind: "native",
    manualHref: "/manual/guis/#omacut",
    name: "Omacut",
    websiteUrl: "https://github.com/omacom-io/omacut",
  },
  {
    aliases: ["image viewer", "imv"],
    appsMenu: true,
    availability: "base",
    description: "Image viewer",
    executable: "imv",
    id: "image-viewer",
    kind: "native",
    manualHref: "/manual/guis/#files",
    name: "Image Viewer",
  },
  {
    aliases: ["disks", "gnome-disks"],
    appsMenu: true,
    availability: "base",
    description: "Disk utility",
    executable: "gnome-disks",
    id: "disks",
    kind: "native",
    manualHref: "/manual/guis/#files",
    name: "Disks",
  },
  ...(
    [
      ["vscode", "VS Code", ["code", "visual studio code"]],
      ["cursor-editor", "Cursor", ["cursor", "cursor editor"]],
      ["zed", "Zed", ["zed"]],
      ["sublime-text", "Sublime Text", ["subl", "sublime", "sublime text"]],
      ["helix", "Helix", ["helix", "hx"]],
      ["vim", "Vim", ["vim"]],
      ["emacs", "Emacs", ["emacs"]],
    ] as const
  ).map(([id, name, aliases]) => ({
    aliases,
    appsMenu: false,
    availability: "optional" as const,
    description: "Alternative editor",
    executable: aliases[0],
    id,
    kind: "native" as const,
    manualHref: "/manual/development-tools/#alternative-editors",
    name,
  })),
  {
    aliases: ["chatgpt desktop", "openai codex desktop"],
    appsMenu: false,
    availability: "optional",
    description: "AI desktop application",
    executable: "openai-codex-desktop",
    id: "chatgpt-desktop",
    kind: "native",
    manualHref: "/manual/ai/#desktop-apps",
    name: "ChatGPT Desktop",
  },
  {
    aliases: ["grok bot", "grok-bot"],
    appsMenu: false,
    availability: "optional",
    description: "AI desktop application",
    executable: "grok-bot",
    id: "grok-bot",
    kind: "native",
    manualHref: "/manual/ai/#desktop-apps",
    name: "Grok Bot",
  },
  {
    aliases: ["lm studio", "lm-studio"],
    appsMenu: false,
    availability: "optional",
    description: "Local model application",
    executable: "lm-studio",
    id: "lm-studio",
    kind: "native",
    manualHref: "/manual/ai/#local-llms",
    name: "LM Studio",
  },
  {
    aliases: ["ollama"],
    appsMenu: false,
    availability: "optional",
    description: "Local model service",
    executable: "ollama",
    id: "ollama",
    kind: "service",
    manualHref: "/manual/ai/#local-llms",
    name: "Ollama",
  },
  {
    aliases: ["evince", "document viewer"],
    appsMenu: true,
    availability: "base",
    description: "PDF viewer",
    executable: "evince",
    id: "document-viewer",
    kind: "native",
    manualHref: "/manual/filling-out-pdfs/",
    name: "Document Viewer",
  },
  {
    aliases: ["xournal", "xournalpp"],
    appsMenu: true,
    availability: "base",
    description: "PDF annotation",
    executable: "xournalpp",
    id: "xournalpp",
    kind: "native",
    manualHref: "/manual/filling-out-pdfs/",
    name: "Xournal++",
  },
  {
    aliases: ["chromium", "browser"],
    appsMenu: true,
    availability: "base",
    description: "Web browser",
    executable: "chromium",
    hotkeys: ["Super + Shift + Return"],
    id: "chromium",
    kind: "native",
    manualHref: "/manual/browsers/",
    name: "Chromium",
    websiteUrl: "https://www.chromium.org/",
  },
  ...[
    ["chrome", "Chrome"],
    ["edge", "Edge"],
    ["brave", "Brave"],
    ["brave-origin", "Brave Origin"],
    ["firefox", "Firefox"],
  ].map(([id, name]) => ({
    aliases: [...new Set([id, name.toLowerCase()])],
    appsMenu: false,
    availability: "optional" as const,
    description: "Web browser",
    executable: id,
    id,
    kind: "native" as const,
    manualHref: id === "firefox" ? "/manual/browsers/#firefox-and-zen" : "/manual/browsers/",
    name,
  })),
  {
    aliases: ["zen", "zen browser"],
    appsMenu: false,
    availability: "optional",
    description: "Web browser",
    executable: "zen-browser",
    id: "zen",
    kind: "native",
    manualHref: "/manual/browsers/#firefox-and-zen",
    name: "Zen",
    websiteUrl: "https://zen-browser.app/",
  },
  ...[
    ["1password", "1Password", "https://1password.com/", "Super + Shift + /"],
    ["bitwarden", "Bitwarden", "https://bitwarden.com/", ""],
    ["spotify", "Spotify", "https://spotify.com/", "Super + Shift + M"],
    ["dropbox", "Dropbox", "https://www.dropbox.com/", ""],
    ["tailscale", "Tailscale", "https://tailscale.com/", ""],
    ["once", "ONCE", "https://once.com/", ""],
    ["nordvpn", "NordVPN", "https://nordvpn.com/", ""],
  ].map(([id, name, websiteUrl, hotkey]) => ({
    aliases: [...new Set([id, name.toLowerCase()])],
    appsMenu: false,
    availability: "optional" as const,
    description: id === "spotify" ? "Music" : "Service",
    hotkeys: hotkey ? [hotkey] : undefined,
    id,
    kind: "service" as const,
    manualHref: `/manual/commercial-apps-services/#${id}`,
    name,
    websiteUrl,
  })),
  ...[
    ["hey", "HEY", "Email and calendar", "https://www.hey.com/", "https://app.hey.com"],
    [
      "basecamp",
      "Basecamp",
      "Project management",
      "https://basecamp.com/",
      "https://launchpad.37signals.com",
    ],
    ["chatgpt", "ChatGPT", "AI assistant", "https://chatgpt.com", "https://chatgpt.com"],
    ["grok", "Grok", "AI assistant", "https://grok.com", "https://grok.com"],
    ["whatsapp", "WhatsApp", "Messenger", "https://www.whatsapp.com/", "https://web.whatsapp.com/"],
    [
      "google-messages",
      "Google Messages",
      "Messenger",
      "https://messages.google.com/",
      "https://messages.google.com/web/conversations",
    ],
    [
      "google-photos",
      "Google Photos",
      "Photos",
      "https://photos.google.com/",
      "https://photos.google.com/",
    ],
    ["google-maps", "Google Maps", "Maps", "https://maps.google.com/", "https://maps.google.com/"],
    [
      "google-contacts",
      "Google Contacts",
      "Contacts",
      "https://contacts.google.com/",
      "https://contacts.google.com/",
    ],
    ["x", "X", "Social network", "https://x.com/", "https://x.com/"],
    ["youtube", "YouTube", "Video", "https://youtube.com/", "https://youtube.com/"],
    ["zoom", "Zoom", "Video meetings", "https://zoom.us/", "https://app.zoom.us/wc/home"],
    [
      "discord",
      "Discord",
      "Communities",
      "https://discord.com/",
      "https://discord.com/channels/@me",
    ],
  ].map(([id, name, description, websiteUrl, launchUrl]) => ({
    aliases: [...new Set([id, name.toLowerCase()])],
    appsMenu: !["chatgpt", "grok"].includes(id),
    availability: "base" as const,
    description,
    id,
    kind: "web-app" as const,
    launchUrl,
    manualHref: `/manual/web-apps/#${id.startsWith("google-") ? "google-apps" : id}`,
    name,
    websiteUrl,
  })),
  ...[
    ["steam", "Steam", "https://store.steampowered.com/"],
    ["retroarch", "RetroArch", "https://www.retroarch.com/"],
    ["xbox-cloud-gaming", "Xbox Cloud Gaming", "https://www.xbox.com/en-US/play"],
    ["nvidia-geforce-now", "NVIDIA GeForce NOW", "https://www.nvidia.com/en-us/geforce-now/"],
    ["minecraft", "Minecraft", ""],
    ["battle-net", "Battle.net", "https://eu.shop.battle.net/en-us"],
    ["lutris-windows-games", "Lutris", "https://lutris.net/"],
    ["heroic-launcher-epic-games", "Heroic Launcher", "https://heroicgameslauncher.com/"],
  ].map(([anchor, name, websiteUrl]) => ({
    aliases: [...new Set([name.toLowerCase(), anchor])],
    appsMenu: false,
    availability: "optional" as const,
    description: "Gaming",
    id: anchor,
    kind: anchor === "xbox-cloud-gaming" ? ("web-app" as const) : ("native" as const),
    launchUrl: anchor === "xbox-cloud-gaming" ? websiteUrl : undefined,
    manualHref: `/manual/gaming/#${anchor === "battle-net" ? "battlenet" : anchor}`,
    name,
    websiteUrl: websiteUrl || undefined,
  })),
  {
    aliases: ["moonlight", "game streaming"],
    appsMenu: true,
    availability: "preinstall",
    description: "Game streaming",
    executable: "moonlight",
    id: "moonlight",
    kind: "native",
    manualHref: "/manual/gaming/#moonlight-game-streaming-from-a-pc",
    name: "Moonlight",
    websiteUrl: "https://github.com/moonlight-stream/moonlight-qt",
  },
  {
    aliases: ["windows", "windows vm"],
    appsMenu: false,
    availability: "optional",
    description: "Windows virtual machine",
    executable: "omarchy-windows-vm",
    id: "windows",
    kind: "vm",
    manualHref: "/manual/windows-vm/#using-it",
    name: "Windows",
  },
];

export const omarchyAppsMenuApplications = omarchyApplications
  .filter((application) => application.appsMenu)
  .toSorted((left, right) =>
    (left.launcherLabel ?? left.name).localeCompare(right.launcherLabel ?? right.name)
  );

const terminalApplicationAliases = new Map(
  omarchyApplications.flatMap((application) =>
    application.aliases.map((alias) => [alias.toLowerCase(), application] as const)
  )
);

export function findTerminalApplication(input: string) {
  return terminalApplicationAliases.get(input.trim().toLowerCase());
}

export function applicationDisplayName(application: OmarchyApplication) {
  return application.launcherLabel ?? application.name;
}
