// Generated by `bun run sync:news`. Do not edit by hand.
import "server-only";
import type { MDXContent } from "mdx/types";

import NewsPost6 from "@/content/news/2026/08/1password-and-37signals-become-distinguished-corporate-patrons.mdx";
import NewsPost9 from "@/content/news/2026/08/100000-downloads-in-a-week.mdx";
import NewsPost10 from "@/content/news/2026/08/introducing-omarchy-air.mdx";
import NewsPost11 from "@/content/news/2026/08/introducing-the-omarchy-rangers.mdx";
import NewsPost15 from "@/content/news/2026/08/omacom-foundation-funding-hits-10m.mdx";
import NewsPost16 from "@/content/news/2026/08/omacom-foundation-launches-with-8-million.mdx";
import NewsPost17 from "@/content/news/2026/08/omacom-foundation-to-be-exclusive-hyprland-sponsor.mdx";
import NewsPost12 from "@/content/news/2026/08/omacom-foundation-to-be-premier-mise-sponsor.mdx";
import NewsPost14 from "@/content/news/2026/08/omacom-foundation-to-be-premier-quickshell-sponsor.mdx";
import NewsPost7 from "@/content/news/2026/08/omacom-foundation-welcomes-brian-armstrong-and-yunjie-dai.mdx";
import NewsPost13 from "@/content/news/2026/08/omarchy-meetups-around-the-world.mdx";
import NewsPost8 from "@/content/news/2026/08/the-first-plugin-competition-winners.mdx";
import NewsPost18 from "@/content/news/2026/08/the-first-plugin-competition.mdx";
import NewsPost1 from "@/content/news/2026/09/omacom-foundation-accelerates-spending-goals.mdx";
import NewsPost3 from "@/content/news/2026/09/omacom-foundation-hires-krzysztof-wilczynski.mdx";
import NewsPost5 from "@/content/news/2026/09/omacom-foundation-reaches-13-million.mdx";
import NewsPost0 from "@/content/news/2026/09/omacom-foundation-secures-tokens-from-leading-labs.mdx";
import NewsPost2 from "@/content/news/2026/09/omacom-patronage-is-open-to-everyone.mdx";
import NewsPost4 from "@/content/news/2026/09/quattro-crosses-200000-iso-downloads.mdx";
import NewsPost19 from "@/content/news/2026/09/the-omarchy-core-team.mdx";

type NewsContentEntry = {
  author: string;
  authorUrl?: string;
  Content: MDXContent;
  dateTime: string;
  description: string;
  publishedOn: string;
  slug: string;
  title: string;
};

export const newsContent: readonly NewsContentEntry[] = [
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost0,
    dateTime: "2026-09-03T19:45:00.000Z",
    description:
      "Meta Superintelligence Labs joins as Founding Token Patron with $1.5 million in tokens, and Anthropic, OpenAI, and Fireworks each add $150,000 as Distinguished Token Patrons.",
    publishedOn: "2026-09-03",
    slug: "2026/09/omacom-foundation-secures-tokens-from-leading-labs",
    title: "Omacom Foundation secures $1.95M in tokens from leading labs",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost1,
    dateTime: "2026-09-03T11:05:00.000Z",
    description:
      "Everything raised this year will be spent over the next three. That means yearly budgets in excess of $4 million for 2027, 2028, and 2029.",
    publishedOn: "2026-09-03",
    slug: "2026/09/omacom-foundation-accelerates-spending-goals",
    title: "Omacom Foundation accelerates spending goals",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost2,
    dateTime: "2026-09-03T11:00:00.000Z",
    description:
      "Patronage of the Omacom Foundation is now open to everyone in four tiers, each with its own badge, and there's more spending on the way.",
    publishedOn: "2026-09-03",
    slug: "2026/09/omacom-patronage-is-open-to-everyone",
    title: "Omarchy Patronage is now open to everyone",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost3,
    dateTime: "2026-09-03T10:12:00.000Z",
    description:
      "The foundation's first full-time employee will lead the Omarchy Kernel work on performance, compatibility, and security.",
    publishedOn: "2026-09-03",
    slug: "2026/09/omacom-foundation-hires-krzysztof-wilczynski",
    title: "Omacom Foundation hires kernel developer Krzysztof Wilczyński",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost4,
    dateTime: "2026-09-02T16:29:00.000Z",
    description:
      "Two hundred thousand Quattro ISOs in under 19 days, downloads from 215 countries and territories, and a date for the first million.",
    publishedOn: "2026-09-02",
    slug: "2026/09/quattro-crosses-200000-iso-downloads",
    title: "Omarchy Quattro crosses 200,000 ISO downloads",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost5,
    dateTime: "2026-09-02T11:03:00.000Z",
    description:
      "Ryan R. Hughes, Ed Huang, Adrien Treccani, and Max Schoening each pledge $100,000, and the foundation hits $13 million.",
    publishedOn: "2026-09-02",
    slug: "2026/09/omacom-foundation-reaches-13-million",
    title: "Omacom Foundation reaches $13M with four Distinguished Patrons",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost6,
    dateTime: "2026-08-31T13:20:00.000Z",
    description:
      "The first two Distinguished Corporate Patrons each pledge $100,000 a year for three years, taking the Omacom Foundation to $12.6 million.",
    publishedOn: "2026-08-31",
    slug: "2026/08/1password-and-37signals-become-distinguished-corporate-patrons",
    title: "1Password and 37signals become Distinguished Corporate Patrons",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost7,
    dateTime: "2026-08-31T13:03:00.000Z",
    description:
      "Two more Founding Patrons join the mission with $1 million each, and the foundation hits $12 million.",
    publishedOn: "2026-08-31",
    slug: "2026/08/omacom-foundation-welcomes-brian-armstrong-and-yunjie-dai",
    title: "Omacom Foundation welcomes Brian Armstrong and Yunjie Dai",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost8,
    dateTime: "2026-08-28T20:58:00.000Z",
    description:
      "Radio Atlas, Omagotchi, and AirPods take the podium in the first Omarchy plugin competition.",
    publishedOn: "2026-08-28",
    slug: "2026/08/the-first-plugin-competition-winners",
    title: "The first plugin competition winners",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost9,
    dateTime: "2026-08-28T18:55:00.000Z",
    description:
      "A hundred thousand people installed Omarchy in seven days, and we moved nearly a petabyte doing it.",
    publishedOn: "2026-08-28",
    slug: "2026/08/100000-downloads-in-a-week",
    title: "Omarchy tops 100,000 downloads in a week",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost10,
    dateTime: "2026-08-28T09:06:00.000Z",
    description:
      "A six-month, funded residency for the artists who make Omarchy beautiful. The first two are HANCORE and OldJobobo.",
    publishedOn: "2026-08-28",
    slug: "2026/08/introducing-omarchy-air",
    title: "Introducing Omarchy AIR",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost11,
    dateTime: "2026-08-27T18:59:00.000Z",
    description:
      "The first Omarchy Rangers are here to help people find their way, and applications are open.",
    publishedOn: "2026-08-27",
    slug: "2026/08/introducing-the-omarchy-rangers",
    title: "Introducing Omarchy Rangers",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost12,
    dateTime: "2026-08-25T18:28:00.000Z",
    description:
      "Third sponsorship out the door! The Omacom Foundation is becoming a premier sponsor of mise, and thereby of jdx, who has spent years building the tool that quietly makes managing different versions of Ruby, Node, Go a joy to manage, and…",
    publishedOn: "2026-08-25",
    slug: "2026/08/omacom-foundation-to-be-premier-mise-sponsor",
    title: "Omacom Foundation to be premier mise sponsor",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost13,
    dateTime: "2026-08-24T11:07:00.000Z",
    description:
      "Find an Omarchy meetup near you or start one yourself and add it to the global calendar.",
    publishedOn: "2026-08-24",
    slug: "2026/08/omarchy-meetups-around-the-world",
    title: "Omarchy meetups around the world",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost14,
    dateTime: "2026-08-24T10:49:00.000Z",
    description:
      "More money in, more money out! Our second major sponsorship from the Omacom Foundation is going to outfoxxed for his superb work on Quickshell. It's only been part of the public release for a week, but it's already crystal clear that it…",
    publishedOn: "2026-08-24",
    slug: "2026/08/omacom-foundation-to-be-premier-quickshell-sponsor",
    title: "Omacom Foundation to be premier Quickshell sponsor",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost15,
    dateTime: "2026-08-24T10:29:00.000Z",
    description:
      "Drew Houston and Peter Steinberger join the Omacom Foundation as Founding Patrons, taking total funding to $10 million.",
    publishedOn: "2026-08-24",
    slug: "2026/08/omacom-foundation-funding-hits-10m",
    title: "Omacom Foundation funding hits $10m",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost16,
    dateTime: "2026-08-21T15:57:00.000Z",
    description:
      "It's time to dream big. Omarchy Quattro has given people a chance to experience what the malleable computer of the future looks like, and they like it (a lot!). It now feels like a moral obligation to make this future more broadly…",
    publishedOn: "2026-08-21",
    slug: "2026/08/omacom-foundation-launches-with-8-million",
    title: "Omacom Foundation launches with $14.95 million",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost17,
    dateTime: "2026-08-21T15:50:00.000Z",
    description:
      "What better way to start spending some of the treasure we just raised for the Omacom Foundation than on the most cracked Linux kid in Poland: Vaxry! As the creator of Hyprland, he's responsible for one of the three core technologies in…",
    publishedOn: "2026-08-21",
    slug: "2026/08/omacom-foundation-to-be-exclusive-hyprland-sponsor",
    title: "Omacom Foundation to be exclusive Hyprland sponsor",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost18,
    dateTime: "2026-08-19T15:26:00.000Z",
    description:
      "The Omarchy Plugin Marketplace is already home to over 500 plugins and growing very fast. We have a million ideas for how we can improve this setup, including with automated agent powered security reviews, but let's not have perfect be…",
    publishedOn: "2026-08-19",
    slug: "2026/08/the-first-plugin-competition",
    title: "The first plugin competition",
  },
  {
    author: "DHH",
    authorUrl: "https://dhh.dk",
    Content: NewsPost19,
    dateTime: "2026-08-19T13:17:00.000Z",
    description:
      "Omarchy's explosive growth demands structured teams in response, and we're going to get started by incorporating The Omarchy Core Team. This group will share the responsibility of driving the direction of our distro, ensuring we continue…",
    publishedOn: "2026-08-19",
    slug: "2026/09/the-omarchy-core-team",
    title: "The Omarchy Core Team",
  },
];
